name: venmotorsport
favicon: null
layout_spectrum: 0.6865328815765679
typography_spectrum: 0.10007218620739877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3993914816528559
  lightness: 0.9128463969100267
  saturation: 0.6474649053998291
  rhythmicContrast: 0.9718414198141545
purpose: []
